# Lightweight Grafana for local Istio POC.
adminUser: admin
adminPassword: admin

persistence:
  enabled: false

service:
  type: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.istio-system.svc.cluster.local
        isDefault: true
