apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-client
  namespace: istio-poc
  labels:
    app: curl-client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: curl-client
  template:
    metadata:
      labels:
        app: curl-client
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curl
          image: curlimages/curl:8.10.1
          imagePullPolicy: IfNotPresent
          command: ["sleep", "3650d"]
          resources:
            requests:
              cpu: 10m
              memory: 24Mi
            limits:
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
